### ISSUE TITLE
Nonce is too small!

### ISSUE THREAD

**Issue by Lucifer-samu** [LocalBitcoins/lbcapi#17]
Traceback (most recent call last):
  File "loc.py", line 7, in <module>
    conn.call('GET', '/api/myself/').json()
  File "/Users/andrew/Library/Python/3.7/lib/python/site-packages/lbcapi-1.0.2-py3.7.egg/lbcapi/api.py", line 131, in call
Exception: Nonce is too small!

**Comment by henu** [comment]
This is not a bug. You must always use bigger nonce than with last call, even between different sessions.

**Comment by Lucifer-samu** [comment]
example?

**Comment by henu** [comment]
Ah I remembered wrong. The library chooses the nonce, and in your case you have used it so fast, that it has selected same nonce twice.

Hmm yeah, this could be fixed. Right now your can bypass the problem by having at least 1 ms time between API calls.
